name: Backend Core CI

on:
  push:
    branches: ["main", "master"]
    paths:
      - "backend/core/**"

jobs:
  backend-core-build:
    name: Backend Core CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/csea-psgtech/codemania_csea-backend-core

    defaults:
      run:
        working-directory: ./backend/core

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/core/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint || echo "No lint configured"

      - name: Build project
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/core
          file: ./backend/core/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:0.1-${{ github.sha }}

      - name: Notify Jenkins
        run: |
          curl --insecure "${{ secrets.JENKINS_BACKEND_URL }}"
